// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-screen/Redesign.tsx": () => import("../components/mockups/login-screen/Redesign.tsx"),
  "./components/mockups/team-screen/Redesign.tsx": () => import("../components/mockups/team-screen/Redesign.tsx")
};
